chore(deps): move most dependencies to blsq-environment image
BLSQ/openhexa-docker-images pull request #42
Opened 2024-08-06 11:19 UTC by cheikhgwane

2024-08-06 15:39 UTC, cheikhgwane commented on images/blsq/Dockerfile
> -USER ${NB_UID}
A package (rgdal ?) needs to update the gdal version installed and fails due to a permission denied.

2024-08-07 10:06 UTC, qgerome requested changes
I also think the awscli can be moved to the legacy image

2024-08-07 10:06 UTC, qgerome commented on images/base/Dockerfile
> -  'fsspec=2023.12.2' \
This is needed everywhere

2024-08-07 10:06 UTC, qgerome commented on images/base/Dockerfile
> -  'gcsfs=2023.12.2' \
This is needed everywhere

2024-08-07 10:06 UTC, qgerome commented on images/base/Dockerfile
> -  'papermill=2.*' \
This is needed everywhere

2024-08-16 14:50 UTC, cheikhgwane commented
@qgerome all tested 👍

2024-08-16 14:55 UTC, merged