feat(Blsq): add ruff linter to blsq image
BLSQ/openhexa-docker-images pull request #60
Opened 2024-11-19 07:53 UTC by cheikhgwane

See [issue](https://bluesquare.atlassian.net/jira/software/c/projects/HEXA/boards/330?assignee=712020%3A1d0055ff-af59-47b7-b48d-4d37e2a0d0b9&selectedIssue=HEXA-1036).

Sample : 

<img width="1437" alt="Screenshot 2024-11-18 at 19 14 01" src="https://github.com/user-attachments/assets/5146b735-44b0-40c1-9cec-630a5f9cc14a">

2024-11-19 12:38 UTC, qgerome requested changes
You added the package but did not handle the `RUFF_CACHE_DIR` as explained in the ticket, why ?

2024-11-19 12:48 UTC, cheikhgwane commented
Fixed now, thx for the notice.

2024-11-19 12:48 UTC, cheikhgwane commented
> You added the package but did not handle the `RUFF_CACHE_DIR` as explained in the ticket, why ?
Updated 
<img width="1437" alt="Screenshot 2024-11-19 at 12 47 49" src="https://github.com/user-attachments/assets/a263325f-5c83-4bb7-8a88-a916091177df">

2024-12-02 14:51 UTC, qgerome approved these changes

2024-12-02 14:52 UTC, merged